permissions:
  contents: write

name: build-docs
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - run: MKDOCS_GIT_COMMITTERS_APIKEY=${{secrets.GITHUB_TOKEN}} mkdocs gh-deploy --force --clean --verbose