name: Deploy MkDocs site
on:
  push:
    branches:
      - main   # change to 'master' if your default branch is named that
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Install MkDocs + all likely plugins used in OpenCentauri
      - run: |
          pip install \
            mkdocs-material \
            mkdocs-glightbox \
            mkdocs-git-committers-plugin-2 \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-minify-plugin \
            pymdown-extensions

      # Build and deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --remote-branch gh-pages
